# Generated by Django 4.1.7 on 2024-04-29 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Iu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('usern_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plataforma.usern')),
                ('grado_academico', models.CharField(max_length=30)),
            ],
            bases=('plataforma.usern',),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usern_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plataforma.usern')),
                ('codigo_sis', models.IntegerField()),
            ],
            bases=('plataforma.usern',),
        ),
        migrations.CreateModel(
            name='UserNRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_activacion', models.DateField()),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.usern')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicado', models.DateField()),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.curso')),
            ],
        ),
        migrations.CreateModel(
            name='RolFuncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.funcion')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionIU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.funcion')),
                ('iu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.iu')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.inscrito')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.entrega')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('archivo', models.BinaryField()),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.entrega')),
                ('tipo_archivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.tipoarchivo')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataforma.docente'),
        ),
    ]
