# Generated by Django 5.0.4 on 2024-05-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_usern_groups_usern_is_staff_usern_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usern',
            old_name='correo',
            new_name='email',
        ),
    ]
