# Generated by Django 5.0.4 on 2024-05-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_rename_correo_usern_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usern',
            name='user',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usern',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
