# Generated by Django 5.0.4 on 2024-05-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_usern_user_alter_usern_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscrito',
            unique_together={('id', 'estudiante', 'curso')},
        ),
    ]
