# Generated by Django 5.0.4 on 2024-05-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_alter_inscrito_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscrito',
            unique_together={('estudiante', 'curso')},
        ),
    ]
