# Generated by Django 5.0.4 on 2024-05-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nombre',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
