# Generated by Django 5.0.4 on 2024-05-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_curso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
